language: node_js

node_js:
  - stable
  - '10'
  - '8'

sudo: false

before_install:
  - npm install -g bumpr@^2.7.2

install:
  - yarn install

before_script:
  - yarn run bumpr check

script:
  - yarn run bumpr is-pr && yarn test

deploy:
  provider: npm
  email: dogmaiobot@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8'
    tags: true
  api_key:
    secure: k6VuYdu2ENSu8iLzeQlQVltsCXv4EExoil7tVzk6ti26fkyqfaML3walfoYlpfAcx3DIEbXWo35Qd4tM0EQRKLfLmflmilKa8CV7ZyUsA3D7fG+8OGFBWLCLAndviHa1SpvQXyu7DYtKfQvs4hHol9dKic15bFa/MZfNxW+6Cgv4nb5gFhTk/LWJpGr0UU6QD1qS0QrGO1rhg9b14eg+Rs29AQkFg4L95VxmsxwOgES2pksXnWfG4L6a+FyDojbt44xxg9ra/u0kyrsk7X/FIKeTqN3bpKbDXxsttbJZykVARoJKAMOqW/rqVeu1WF6bUJaCSKIrVG2h9we/XX6fuVU9rpmvpb+QF42cachdGsdjGaqx3yDVVD/SEeAtiqW+zeggYePX8xC5v+Z59IkB1qIRXAfQDdfkUX2tbOXa6lxDnpFiBiCqOcrrCvrH8olcZynJ4lJ3YnDO+LWlgkcnQvLU8RoS9wf5yOteGVi8XD3+XfUYH9eAxocvDn189UwkZL8Ws8qSEiyJLDzuUWzeA32wBFro0xj7YwTt9R8MxQcUekfUHSx/Kt0zWjaYdRlm3638m32NleScSP4G8EWK7T6r1hwQVSN+qE8PW90ERnEKdRwpAvr1T7CAqTthelZRJcnqrMDYDlub3jlxAmj8o7+oBxiiMskTCKCNuhFFoBM=
